name: server

on:
  push:
    paths:
    - '.github/workflows/server.yaml'
    - 'server/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'server: Install dependencies'
        working-directory: server
        run: npm ci
      - name: 'server: Lint'
        working-directory: server
        run: npm run lint --if-present
      - name: 'server: Build'
        working-directory: server
        run: npm run build --if-present
      - name: 'server: Test'
        working-directory: server
        run: npm run test --if-present
