name: web

on:
  push:
    paths:
    - '.github/workflows/web.yaml'
    - 'web/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 'web: Install dependencies'
        working-directory: web
        run: npm ci
      - name: 'web: Lint'
        working-directory: web
        run: npm run lint --if-present
      - name: 'web: Build'
        working-directory: web
        run: npm run build --if-present
      - name: 'web: Test'
        working-directory: web
        run: npm run test --if-present